#!/usr/bin/env node
/**
 * build.js — Scans image folders and writes gallery-data.js
 * Run after adding or removing images:   node build.js
 *
 * The generated gallery-data.js is committed to git so GitHub Pages
 * can serve the full portfolio with zero server-side code.
 */

const fs   = require('fs');
const path = require('path');

const TAB_FOLDERS = {
  table:    'images/The Table',
  lookbook: 'images/The Lookbook',
  brand:    'images/The Brand',
  occasion: 'images/The Occasion',
};

const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.JPG', '.JPEG', '.png', '.PNG', '.webp', '.WEBP']);

console.log('\nScanning image folders...\n');

const data = {};

for (const [key, folder] of Object.entries(TAB_FOLDERS)) {
  const folderPath = path.join(__dirname, folder);
  try {
    const files = fs.readdirSync(folderPath)
      .filter(f => IMAGE_EXTS.has(path.extname(f)))
      .sort((a, b) => a.localeCompare(b));
    data[key] = files;
    console.log(`  ${key.padEnd(12)} ${String(files.length).padStart(2)} images   ← ${folder}`);
  } catch (e) {
    console.warn(`  ⚠  Could not read ${folder}: ${e.message}`);
    data[key] = [];
  }
}

const output = `// Auto-generated by build.js — do not edit manually.
// To update: add/remove images from the folders, then run:  node build.js
const GALLERY_DATA = ${JSON.stringify(data, null, 2)};
`;

fs.writeFileSync(path.join(__dirname, 'gallery-data.js'), output, 'utf8');

// Cache-bust index.html so returning visitors always load fresh gallery data
const htmlPath = path.join(__dirname, 'index.html');
let html = fs.readFileSync(htmlPath, 'utf8');
const version = Date.now();
html = html.replace(/src="gallery-data\.js(\?v=\d+)?"/, `src="gallery-data.js?v=${version}"`);
fs.writeFileSync(htmlPath, html, 'utf8');

console.log(`\n✦  gallery-data.js written.\n✦  index.html cache-busted with ?v=${version}\n`);
