// Auto-generated by build.js — do not edit manually.
// To update: add/remove images from the folders, then run:  node build.js
const GALLERY_DATA = {
  "table": [
    "_DSC1970-1.jpg",
    "_DSC2003.jpg",
    "_DSC2059-2.jpg",
    "_DSC2073-2.jpg",
    "_DSC2084-1.jpg",
    "_DSC7030.jpg",
    "_DSC7038-1.jpg",
    "_DSC7172.jpg",
    "_DSC7208.jpg",
    "_DSC7229.jpg"
  ],
  "lookbook": [
    "_DSC9576.jpg",
    "_DSC9814[1]-final.jpg",
    "DSC00305.jpg",
    "DSC01861-Enhanced-NR.jpg",
    "DSC02368.jpg",
    "DSC02612-Enhanced-NR.jpg",
    "DSC07581.jpg",
    "DSC07788-1.jpg",
    "DSC07949-1.jpg",
    "DSC08515.jpg",
    "DSC08526.jpg"
  ],
  "brand": [
    "_DSC2115-1.jpg",
    "_DSC7401.jpg",
    "_DSC7476.jpg",
    "_DSC7749.jpg",
    "_DSC8544-1.jpg",
    "_DSC8614.jpg",
    "_DSC9221.jpg",
    "_DSC9539.jpg",
    "DSC06762-Enhanced-NR-1.jpg",
    "DSC06806.jpg"
  ],
  "occasion": [
    "_DSC0126.jpg",
    "_DSC0149.jpg",
    "_DSC0198.jpg",
    "_DSC0596.jpg",
    "_DSC9440.jpg",
    "_DSC9457.jpg",
    "_DSC9552.jpg",
    "_DSC9559.jpg",
    "_DSC9645.jpg",
    "_DSC9957-1.jpg"
  ]
};
