// Auto-generated by build.js — do not edit manually.
// To update: add/remove images from the folders, then run:  node build.js
const GALLERY_DATA = {
  "table": [
    {
      "file": "_DSC1970-1.jpg"
    },
    {
      "file": "_DSC2003.jpg"
    },
    {
      "file": "_DSC2059-2.jpg"
    },
    {
      "file": "_DSC2073-2.jpg"
    },
    {
      "file": "_DSC2084-1.jpg"
    },
    {
      "file": "_DSC6990.jpg"
    },
    {
      "file": "_DSC7030.jpg"
    },
    {
      "file": "_DSC7038-1.jpg"
    },
    {
      "file": "_DSC7172.jpg"
    },
    {
      "file": "_DSC7208.jpg"
    },
    {
      "file": "_DSC7229.jpg"
    }
  ],
  "lookbook": [
    {
      "file": "_DSC9576.jpg"
    },
    {
      "file": "_DSC9814[1]-final.jpg"
    },
    {
      "file": "DSC00305.jpg"
    },
    {
      "file": "DSC01861-Enhanced-NR.jpg"
    },
    {
      "file": "DSC02368.jpg"
    },
    {
      "file": "DSC02612-Enhanced-NR.jpg"
    },
    {
      "file": "DSC07581.jpg"
    },
    {
      "file": "DSC07788-1.jpg"
    },
    {
      "file": "DSC07949-1.jpg"
    },
    {
      "file": "DSC08515.jpg"
    },
    {
      "file": "DSC08526.jpg"
    }
  ],
  "brand": [
    {
      "file": "_DSC2115-1.jpg"
    },
    {
      "file": "_DSC7401.jpg"
    },
    {
      "file": "_DSC7476.jpg"
    },
    {
      "file": "_DSC7749.jpg"
    },
    {
      "file": "_DSC8544-1.jpg"
    },
    {
      "file": "_DSC8614.jpg"
    },
    {
      "file": "_DSC9221.jpg"
    },
    {
      "file": "_DSC9539.jpg"
    },
    {
      "file": "DSC06762-Enhanced-NR-1.jpg"
    },
    {
      "file": "DSC06806.jpg"
    }
  ],
  "occasion": [
    {
      "file": "_DSC0126.jpg"
    },
    {
      "file": "_DSC0149.jpg"
    },
    {
      "file": "_DSC0198.jpg"
    },
    {
      "file": "_DSC0596.jpg"
    },
    {
      "file": "_DSC9440.jpg"
    },
    {
      "file": "_DSC9457.jpg"
    },
    {
      "file": "_DSC9552.jpg"
    },
    {
      "file": "_DSC9559.jpg"
    },
    {
      "file": "_DSC9645.jpg"
    },
    {
      "file": "_DSC9957-1.jpg"
    }
  ]
};
