/* ============================================================
   Ammu Cherlakadan — Photography Portfolio
   ============================================================ */

// ── Nav: transparent → filled on scroll ─────────────────────
const nav = document.getElementById('nav');

function updateNav() {
  if (window.scrollY > 60) {
    nav.classList.add('scrolled');
  } else {
    nav.classList.remove('scrolled');
  }
}

window.addEventListener('scroll', updateNav, { passive: true });
updateNav();

// ── Hero bg: slow zoom-in on load ───────────────────────────
const heroBg = document.getElementById('heroBg');
if (heroBg) {
  // Small delay so transition is visible
  requestAnimationFrame(() => {
    setTimeout(() => heroBg.classList.add('loaded'), 100);
  });
}

// ── Mobile nav toggle ────────────────────────────────────────
const navToggle  = document.getElementById('navToggle');
const navOverlay = document.getElementById('navOverlay');
const overlayLinks = document.querySelectorAll('.overlay-link');

function closeMenu() {
  navToggle.classList.remove('open');
  navOverlay.classList.remove('open');
  navToggle.setAttribute('aria-expanded', 'false');
  document.body.style.overflow = '';
}

navToggle.addEventListener('click', () => {
  const isOpen = navOverlay.classList.toggle('open');
  navToggle.classList.toggle('open', isOpen);
  navToggle.setAttribute('aria-expanded', String(isOpen));
  document.body.style.overflow = isOpen ? 'hidden' : '';
});

overlayLinks.forEach(link => link.addEventListener('click', closeMenu));

// Close on Escape
document.addEventListener('keydown', e => {
  if (e.key === 'Escape') closeMenu();
});

// ── Folder → tab mapping ──────────────────────────────────────
// To add a new category: add a new tab button in index.html
// and add a matching entry here. Images load automatically
// from the folder — no other changes needed.
const TAB_FOLDERS = {
  table:    { folder: 'images/The Table',    alt: 'Food & product photography by Ammu Cherlakadan' },
  lookbook: { folder: 'images/The Lookbook', alt: 'Fashion photography by Ammu Cherlakadan' },
  brand:    { folder: 'images/The Brand',    alt: 'Brand photography by Ammu Cherlakadan' },
  occasion: { folder: 'images/The Occasion', alt: 'Event photography by Ammu Cherlakadan' },
};

// ── Build masonry from pre-generated gallery-data.js ─────────
// gallery-data.js is generated by running:  node build.js
// It defines GALLERY_DATA = { table: [...], lookbook: [...], ... }
function buildMasonry(tabKey, masonryEl) {
  if (masonryEl.children.length > 0) return;   // already built

  const config = TAB_FOLDERS[tabKey];
  if (!config) return;

  const files = (typeof GALLERY_DATA !== 'undefined' && GALLERY_DATA[tabKey]) || [];

  const fragment = document.createDocumentFragment();
  files.forEach(filename => {
    const item = document.createElement('div');
    item.className = 'masonry-item';
    const img = document.createElement('img');
    img.src     = `${config.folder}/${filename}`;
    img.alt     = config.alt;
    img.loading = 'lazy';
    img.onload  = img.onerror = () => item.classList.add('loaded');
    item.appendChild(img);
    fragment.appendChild(item);
  });
  masonryEl.appendChild(fragment);
}

// Build first visible tab immediately on load
(function initGallery() {
  const activePanel = document.querySelector('.tab-panel.active');
  if (activePanel) {
    const key = activePanel.id.replace('panel-', '');
    buildMasonry(key, activePanel.querySelector('.masonry'));
  }
})();

// ── Portfolio tabs ───────────────────────────────────────────
const tabBtns   = document.querySelectorAll('.tab-btn');
const tabPanels = document.querySelectorAll('.tab-panel');

tabBtns.forEach(btn => {
  btn.addEventListener('click', () => {
    const target = btn.dataset.tab;

    // Update buttons
    tabBtns.forEach(b => {
      b.classList.remove('active');
      b.setAttribute('aria-selected', 'false');
    });
    btn.classList.add('active');
    btn.setAttribute('aria-selected', 'true');

    // Show correct panel + lazy-load its images on first open
    tabPanels.forEach(panel => {
      const isTarget = panel.id === `panel-${target}`;
      panel.classList.toggle('active', isTarget);
      if (isTarget) {
        buildMasonry(target, panel.querySelector('.masonry'));
      }
    });
  });
});

// ── Scroll reveal ─────────────────────────────────────────────
const revealEls = document.querySelectorAll('.reveal');

const revealObserver = new IntersectionObserver(
  (entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        revealObserver.unobserve(entry.target);
      }
    });
  },
  { threshold: 0.12, rootMargin: '0px 0px -40px 0px' }
);

revealEls.forEach(el => revealObserver.observe(el));

// ── Smooth nav link scrolling (offset for fixed nav) ─────────
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
  anchor.addEventListener('click', function (e) {
    const target = document.querySelector(this.getAttribute('href'));
    if (!target) return;
    e.preventDefault();

    const navHeight = nav.offsetHeight;
    const top = target.getBoundingClientRect().top + window.scrollY - navHeight;

    window.scrollTo({ top, behavior: 'smooth' });
  });
});
